num_faulty_nodes: 1 # f
num_nodes: 4 # >= 3f + 1
stationary: True
sleep_sec: 60
node_sleep: .1
steps: 10000
min_fail_fraction: 0.5

# Failure prob set by environment
fail_prob:
  # Initial prob.
  init:
    mean: 0.2
    std: 0.1
  # Update delta prob.
  update:
    mean: 0.05
    std: 0.01
    inc_split: 0.5 # Fraction of nodes to increase failure prob

# Initial failure estimates
failure_estimates:
  mean: 0.1
  std: 0.05

# Simpliest leader election
v1:
  epsilon: 0.1
  decay: 0.99
  alpha: 0.1

#client
client:
  num_requests: 20

#ports
port:
  client_port : 65000
  replica_base_port : 49154